[package]
name = "actix-sample"
version = "0.1.0"
authors = ["Takehiro Ohtani <isit7a@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
futures = "0.3.13"
serde = "1.0.125"
serde_json = "1.0.64"